name: Build, Push Docker Image & Deploy to EC2

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: physics-tutoring-app
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/physics-tutoring-app

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image to Docker Hub
        run: |
          docker build -t $DOCKERHUB_REPO .
          docker push $DOCKERHUB_REPO

  deploy-to-ec2:
    name: Deploy Docker Container to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "--- Installing Docker if not present ---"
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo usermod -aG docker ubuntu
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            echo "--- Checking what is using port 80 ---"
            sudo lsof -i :80 || true

            echo "--- Killing processes using port 80 ---"
            sudo fuser -k 80/tcp || true
            pids=$(sudo lsof -ti :80)
            if [ -n "$pids" ]; then
              echo "Force killing remaining PIDs: $pids"
              sudo kill -9 $pids || true
            fi

            echo "--- Stopping Docker container if it exists ---"
            sudo docker rm -f physics-tutoring-app || true

            echo "--- Restarting Docker service ---"
            sudo systemctl restart docker
            sleep 5

            echo "--- Checking port 80 again ---"
            sudo lsof -i :80 || echo "Port 80 is free"

            echo "--- Pulling latest image and running container on port 80 ---"
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/physics-tutoring-app
            sudo docker run -d --name physics-tutoring-app -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/physics-tutoring-app
